version: '3'
services:
    webapp:
        image: q_app_img
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "5555:5555"
    redis:
        image: redis
        restart: always
        volumes:
            - .docker_volumes/redis:/data
        #    - ./config/redis.conf:/redis.conf
        ports:
            - "6379:6379"
        #command: [ "redis-server", "/redis.conf" ]

    #vnginx:
    #    image: nginx:latest
    #    ports:
    #        - "80:80" 
    #    env_file:
    #        - db.env
    #    volumes:
    #        - ./config/nginx/conf.d:/etc/nginx/conf.d
    #        #- ./var/www/dist:/var/www/dist
    #    depends_on:
    #        - webapp
