version: '3'
services:
    webapp:
        image: q_app_img
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "5555:5555"
    #vnginx:
    #    image: nginx:latest
    #    ports:
    #        - "80:80" 
    #    env_file:
    #        - db.env
    #    volumes:
    #        - ./config/nginx/conf.d:/etc/nginx/conf.d
    #        #- ./var/www/dist:/var/www/dist
    #    depends_on:
    #        - webapp
