version: '3'
services:

    rabbit_worker:
        image: rabbit_worker_img
        build:
            context: .
            dockerfile: Dockerfile_rabbit_worker
        depends_on:
            #- redis
            - rabbit
        env_file:
            - app.env

    celery_worker:
        image: celery_worker_img
        build:
            context: .
            dockerfile: Dockerfile_celery_worker
        depends_on:
            - redis
            - rabbit
        env_file:
            - app.env

    redis_pubsub_worker:
        image: redis_pubsub_worker_img
        build:
            context: .
            dockerfile: Dockerfile_redis_pubsub_worker
        depends_on:
            - redis
        env_file:
            - app.env

    webapp:
        image: q_app_img
        build:
            context: .
            dockerfile: Dockerfile_flask
        ports:
          - "5555:5555"
        depends_on:
            - redis
            - rabbit
        env_file:
            - app.env


    redis:
        image: redis
        restart: always
        #volumes:
        #    - .docker_volumes/redis/data:/data
        ##    - ./config/redis.conf:/redis.conf
        ports:
            - "6379:6379"
        #command: [ "redis-server", "/redis.conf" ]
    rabbit:
        image: rabbitmq:3-management
        restart: always
        #volumes: 
        #    - .docker_volumes/rabbitmq/data:/var/lib/rabbitmq/
        #    - .docker_volumes/rabbitmq/logs:/var/log/rabbitmq/
        #    - .docker_volumes/rabbitmq/etc/:/etc/rabbitmq/

        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=mq
            #- RABBITMQ_DEFAULT_VHOST=my_vhost
        ports:
            - "5672:5672"
            - "15672:15672"

    #vnginx:
    #    image: nginx:latest
    #    ports:
    #        - "80:80" 
    #    env_file:
    #        - db.env
    #    volumes:
    #        - ./config/nginx/conf.d:/etc/nginx/conf.d
    #        #- ./var/www/dist:/var/www/dist
    #    depends_on:
    #        - webapp
